kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-openshift
  template:
    metadata:
      labels:
        app: test-openshift
    spec:
      containers:
        - name: test-openshift
          image: python-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: test-openshift
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: python-app